---
author: Marshall Brown 
date: "2020-04-16"
title: About 
---


[Websters dictionary](https://www.merriam-webster.com/dictionary/about?src=search-dict-hed) defines "about" as: 

> about, adverb: reasonably close to 

which honestly I thought would be more helpful^[I didn't. The goof was meticulously planned from [The Beginning.](https://en.wikipedia.org/wiki/John_1:1https://en.wikipedia.org/wiki/John_1:1)]--but now I'm kind of flustered and want to bail on this whole idea to "do a blog" about "things" I am "interested" in^[data, R, being a human, music, adding to this list is now causing me anxiety] and "try to impress" the unfortunate beings who happen to click on something that [commands](https://en.wikipedia.org/wiki/Imperative_mood) their computer to show screen pixels that reveal this sentence^[yikes]. 

In conclusion, this is a place where patterns emerge on a server^[someone at team netlify knows where] due to the vibrations of my brain^[I have nothing to do with it--I'm just along for the ride like you^[It's a somewhat Malkovichian.]]. [It will soon become extremely vpopular](https://en.wikipedia.org/wiki/The_Secret_(book)), since I plan to model it after McBeth's characterization of life itself^[act 5, sc. 5]. 

Plus I live in the Skagit Valley, which explains the rest.  
